# Generated by Django 3.2.7 on 2021-09-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='Title', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='topic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
